### ISSUE TITLE
Allow setting rotation offset for the pie

### ISSUE THREAD

**Issue by molikuner** [markusfisch/PieLauncher#100]
# Problem

It's not possible to have an app in the bottom center of the pie when 6 apps are used in the pie.

# Solution

Allow the user to rotate the pie (potentially similar how the pie can be resized).

# Use case

I came back to this launcher after some time switching between others and now I'm missing the possibility to swipe down to open the notification shade. I wrote [this small app](https://github.com/molikuner/android-notification-shade) to allow me to open the notification shade by "opening an app". Though now the problem is that I can't just swipe down, but instead need to swipe at a (slight) angle.

**Comment by markusfisch** [comment]
Wow, this is really creative to use a small app to open the notification shade! 👍 

I totally understand that you want to rotate the pie in this case, and I was playing with the idea of adding rotation ever since (it's even supported by the pie drawing code already). I just thought it would probably of no use for anybody and so this feature isn't exposed yet. But I will add this to the pie editor in the next couple of days!

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/PieLauncher/commit/60199db8bbb1003d29635f89f1a51104b534ce7f

Will be in the next update!
