### ISSUE TITLE
Pie Menu Crash

### ISSUE THREAD

**Issue by clshi2022** [markusfisch/PieLauncher#109]
Not sure if it is a common bug, but the Pie Menu crash on me 95% of the time when trying to move them around in editor mode
It's only the icons between 9 o'clock to 12 o'clock, as shown in this [video](https://www.youtube.com/shorts/_jxJ15znxao)

I am using Asus Zenfone 9
Latest official Firmware
Android 14
No root, no hacks

**Comment by markusfisch** [comment]
Hi, and thanks a lot for filing an issue about this! 👍  And for providing the video! I had no idea of this bug 🙈

Fixed in https://github.com/markusfisch/PieLauncher/commit/c3331ca715b0d5cf806b55bb4a1c3ca14a228515

A new [version](https://github.com/markusfisch/PieLauncher/releases/tag/1.19.3) is already on its way through Google Play and should become available soon.
