### ISSUE TITLE
Highlight remove/uninstall areas when dragging app over them

### ISSUE THREAD

**Issue by Aiz0** [markusfisch/PieLauncher#58]
When dragging an app over the remove and uninstall areas It would be nice if they changed color to highlight what action would be taken when the app is dropped.

Additionally, showing the action name  when hovered over could be nice.

**Comment by einmeterhecht** [comment]
Another thing to improve along with this - the uninstall button actually isn't an uninstall button. Should the trash bin icon replaced by an info icon?

**Comment by markusfisch** [comment]
@Aiz0 Good idea! I will try something along these lines!

@einmeterhecht Well, then how would a user know what to do when he/she wants to uninstall an app?

My assumption is that it's much more likely that a user want to uninstall an app than to want info about it. And because you can uninstall from the info panel, this is a good compromise, don't you think?

**Comment by einmeterhecht** [comment]
I do.
Play Store also doesn't like apps that request other apps to be deleted (if Play Store is relevant for pielauncher...)

**Comment by markusfisch** [comment]
Implemented in [version 1.18.0](https://github.com/markusfisch/PieLauncher/releases/tag/1.18.0).
