### ISSUE TITLE
Shadows for pie menu icons 

### ISSUE THREAD

**Issue by Aiz0** [markusfisch/PieLauncher#62]
Have you thought about adding shadows to the pie menu icons?
I think it would look quite good since it would elevate the icons above the wallpaper.

There are also situations were shadows would help substantially with the visibility of the icons.
If someone uses a single color wallpaper and has an app with the same color icon it becomes difficult to see the icon since they blend together.

**Comment by markusfisch** [comment]
I tried adding shadows in a branch, but somehow I really didn't like the look of the icons getting smaller because of the shadows 😞  Here's a screenshot of how that looked like:

![shadows](https://github.com/markusfisch/PieLauncher/assets/485246/9ab39ea1-c6f4-4ff4-b46b-a6ffbed792c8)

Instead, I just added an option to darken the background when the pie menu is visible:

https://github.com/markusfisch/PieLauncher/assets/485246/343667e9-5db2-4e45-92ca-9bf7ce68d97e

This is available in version [1.15.0](https://github.com/markusfisch/PieLauncher/releases/tag/1.15.0) (where it must be enabled in the settings). This version is already on it's way through Google Play and should become available shortly.
