### ISSUE TITLE
Hold to lock the screen

### ISSUE THREAD

**Issue by foxjaw** [markusfisch/PieLauncher#69]
In the current implementation hold does nothing. Did you think of any feature implementation for it ? I prefer locking the screen either by accessibility method (power button) or root method if exists.

**Comment by markusfisch** [comment]
Adding an action for a long press would interfere with using the pie menu. I've tried this multiple times, and found it to be very inconvenient, even if I knew that the action is there.

Because the pie menu only appears when you touch the screen, you usually need a short moment to find your way around, especially if you are not yet used to using it. This short moment would almost always pass the threshold for a long press, what makes using the pie menu quite tricky and possibly even annoying.
