### ISSUE TITLE
Rotating is confusing

### ISSUE THREAD

**Issue by TheLastProject** [markusfisch/PieLauncher#7]
I noticed it's possible to rotate the icons during editing, but I keep doing it accidentally instead of on purpose and it's unclear how to do it purposefully.

Maybe it's an idea to instead make the rotation not be drag-based but have a left arrow above the + sign on the edit screen and a right arrow above the checkmark sign to make the rotation feature more obvious and easier to trigger on purpose and harder to trigger accidentally?

**Comment by markusfisch** [comment]
Well, actually, the rotation is just a result of how the grabbed icon is inserted into the menu. But I can totally see why it's irritating 😬  It's one of these things you never notice when you wrote it 😉 Thanks for bringing it to my attention 👍 

In the current strategy, the ungrabbed icons in the menu maintain their order but not necessarily their position in the menu. This can be seen, for example, when an icon is dragged from 3'o clock position (which is the first menu item) to 2'o clock (which is the last menu item in the menu's internal listing). Then the dragged icon is inserted at the end of the list and the first position (at 3'o clock) will become the first of the ungrabbed icons what makes the whole menu rotate one cell counter-clockwise.

https://user-images.githubusercontent.com/485246/112533904-bd9be780-8daa-11eb-99de-e3095d21a50c.mp4

Not so nice. Alternatively the grabbed icon could simply swap places with the one that occupied the cell before.

https://user-images.githubusercontent.com/485246/112533945-cb516d00-8daa-11eb-93d9-2cb2a10e351e.mp4

Looks much better, but this also means it's much easier to completely scramble the menu order:

https://user-images.githubusercontent.com/485246/112533983-d86e5c00-8daa-11eb-9a47-7677937218ce.mp4

So, I'm not sure if this is the better option because it may confuse even more if the menu gets completely scrambled just by dragging an icon around 🤔

**Comment by TheLastProject** [comment]
The third video sadly does not load for me, so I have trouble understanding the downside. The second video does show what I think would be the correct fix but yeah, cannot tell the risk like this.

**Comment by markusfisch** [comment]
Just fixed it 😉

**Comment by TheLastProject** [comment]
Ah, I see what you mean now... Well, I think the swap version is likely to be less often confusing, but I understand why that's not perfect... It should make small adjustments easier to recover from though, especially if it's around the 3 'o clock area I would think.

**Comment by markusfisch** [comment]
Hm, yes, seems so 🤔 I guess I have to test drive this a little bit 😉 

Right now, there are ugly cases like when you add an icon from the upper half of the screen, and then slowly drag it down the screen to drop it over the removal field, it'll change the order of the existing menu 😬

**Comment by TheLastProject** [comment]
Oh, that is indeed a problematic edge case :(

**Comment by markusfisch** [comment]
What about if any accidental change (of the menu items) from adding a new icon and immediately removing it again is rolled back after editing the menu? (check where the Chrome icon is before removing the new icon)

https://user-images.githubusercontent.com/485246/113507448-c9c23a80-954a-11eb-84fd-69e4c18c7d5d.mp4

This way there wouldn't be this confusing rotation _while_ editing the menu and just entering edit mode (and dragging a new item around) wouldn't change the menu.

Although it is possible to change the order of items just by dragging an item around (as long as the item isn't removed from the menu):

https://user-images.githubusercontent.com/485246/113507546-8a481e00-954b-11eb-908c-71f5a9a4c109.mp4

I'm not sure if this behaviour is clear and logical or still confusing 😉 What do you think?

**Comment by TheLastProject** [comment]
It still confuses me a bit in the second example. I decided to use an image editor change-by-change with what behaviour I would expect. On the left side is your video, on the right side is the state I would have expected.

At the start, it is obviously the same:
![image](https://user-images.githubusercontent.com/1885159/113508106-6f2add80-954e-11eb-85e4-15fbd3641604.png)

But at the first change, it already starts to differentiate:
![image](https://user-images.githubusercontent.com/1885159/113508223-0db73e80-954f-11eb-9ac2-031852ff9ece.png)

I would have expected Binary Eye to take the 3 'o clock position (so, swapping with Chrome's starting position), but instead Binary Eye seems to move to 2 'o clock?

But then I started to look at it more closely, and I think what I am expecting is actually what is happening, it is just hard to tell because you make so many changes so quickly? If they indeed swap like that, it would be the behaviour I'm expecting, but it's hard to tell from the animations. Could you maybe let Chrome go after each move you make it make the behaviour easier to follow?

**Comment by markusfisch** [comment]
I think the only difference at the first change is the zooming animation 😉 The order of the icons is the same and if I would drop the Chrome icon in this frame (the left one), the menu would look exactly like it does in the right image. Binary Eye just _seems_ to be at 2'o clock because of the zooming animation/displacement.

Here's a slower version:
https://user-images.githubusercontent.com/485246/113582248-6a3a5c80-9628-11eb-9194-a48889ce83a8.mov

**Comment by TheLastProject** [comment]
Thanks for the slower version, that is then 100% would would for me be logical behaviour, yeah :)

**Comment by markusfisch** [comment]
Okay, I just merged this in to master: https://github.com/markusfisch/PieLauncher/commit/9d647cbea92928bcb583296073bf0de8b31ae41b

So the next version will sport this behaviour 😄 Thanks for your help 👍
